default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
    -   id: ruff
        types_or:
        - python
        - pyi
        args:
        - --fix
        - --exit-non-zero-on-fix
        - --show-fixes
        - --unsafe-fixes
    -   id: ruff-format
        types_or:
        - python
        - pyi
