[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "site-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Albert M", email = "rinkorn.alb@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.0.3",
    "numpy>=2.2.3",
    "openreview-py>=1.46.3",
    "pandas>=2.2.3",
    "python-slugify>=8.0.4",
    "requests>=2.32.3",
    "selenium>=4.29.0",
    "webdriver-manager>=4.0.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
lint = [
    "ruff>=0.9.10",
    "types-requests>=2.32.0.20250306",
    "types-tqdm>=4.67.0.20250301",
]
test = [
    "pytest>=8.3.5",
]
